language: rust
rust:
  - stable
  - beta
sudo: false
before_script:
  - pip install 'travis-cargo<0.2' --user && export PATH=$HOME/.local/bin:$PATH
  - export RUST_LOG=bobble=debug
script:
  - export CARGO_TARGET_DIR=`pwd`/target
  - cargo test
after_success:
  - travis-cargo coveralls --no-sudo
notifications:
  email:
    on_success: never
os:
  - linux
addons:
  apt:
    sources:
      - kalakris-cmake
    packages:
      - cmake
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
