[workspace]
resolver = "2"
members = [
    "hyper_cgi",
    "josh-core",
    "josh-filter",
    "josh-proxy",
    "josh-rpc",
    "josh-ssh-shell",
    "josh-ui",
]

[profile.release]
lto = true
opt-level = 3
codegen-units = 1

[workspace.dependencies]
defer = "0.1.0"
env_logger = "0.10.2"
futures = "0.3.30"
gix = "0.54.1"
hyper-reverse-proxy = "0.5.1"
lazy_static = "1.4.0"
libc = "0.2.153"
regex = "1.10.3"
rs_tracing= { version = "1.1.0", features = ["rs_tracing"] }
serde = { version = "1.0.197", features = ["std", "derive"] }
serde_json = "1.0.114"
serde_yaml = "0.9.32"
toml = "0.8.10"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }

[workspace.dependencies.git2]
default-features = false
version = "0.18.2"

[workspace.dependencies.juniper]
version = "0.15.12"
default-features = false
features = ["expose-test-schema"]

[workspace.dependencies.tokio]
version = "1.36.0"
features = [
    "fs",
    "rt-multi-thread",
    "macros",
    "io-std",
    "io-util",
    "net",
    "process",
    "signal",
]

[workspace.dependencies.tokio-util]
version = "0.7.10"
features = ["compat"]

[workspace.dependencies.reqwest]
version = "0.11.25"
default-features = false
features = ["blocking", "json"]

[workspace.dependencies.tracing]
version = "0.1.40"
features = ["max_level_trace", "release_max_level_trace"]

[workspace.dependencies.clap]
version = "4.5.2"
features = ["derive", "help", "std", "usage"]
default-features = false
