[package]
name = "josh"
version = "0.2.0"
repository = "https://github.com/esrlabs/josh"
authors = ["Christian Schilling <christian.schilling@esrlabs.com>"]
license = "MIT"
license-file = "LICENSE"
description = "GIT virtualization proxy"
keywords = ["git", "monorepo", "workflow", "scm"]
readme = "README.md"
edition = "2018"

[dependencies]
git2 = "0.10"
clap = "2"
log = "0.4"
tracing = { version = "*", features = ["max_level_trace", "release_max_level_warn"] }
tracing-opentelemetry = "*"
opentelemetry = "*"
tracing-log = "*"
tracing-futures = "*"
tracing-subscriber = "0.2.0-alpha.4"
regex = "1.1"
futures = "0.1"
tokio-core = "0.1"
tokio-process = "0.2"
tokio-io = "0.1"
ring = "0.14"
lazy_static = "1.2"
hyper = "0.11"
futures-cpupool = "0.1"
rust-crypto = "0.2"
pest_derive = "2.1"
pest= "2.1"
rand= "0.6"
serde_json= "1.0"
rs_tracing= { version = "1.0", features = ["rs_tracing"]}
reqwest= "0.9"

