[package]
name = "bobble"
version = "0.1.0"
authors = ["Christian Schilling <christian.schilling@esrlabs.com>"]

[dependencies]
git2 = "*"
clap = "2"
tempdir = "0.3.*"
log = "*"
fern = "*"
env_logger = "*"
regex = "*"
futures = "*"
tokio-core = "*"
tokio-process = "*"
ring = "*"
lazy_static = "*"
hyper = "*"
futures-cpupool = "*"
