[package]
name = "josh"
version = "0.1.0"
authors = ["Christian Schilling <christian.schilling@esrlabs.com>"]
build = "build.rs"
license = "MIT"
description = "GIT virtualization proxy"

[build-dependencies]
git-version = "0.2"

[dependencies]
git2 = "0.10"
clap = "2"
log = "0.4"
fern = "0.5"
regex = "1.1"
futures = "0.1"
tokio-core = "0.1"
tokio-process = "0.2"
tokio-io = "0.1"
ring = "0.14"
lazy_static = "1.2"
hyper = "0.11"
futures-cpupool = "0.1"
rust-crypto = "0.2"
pest_derive = "2.1"
pest= "2.1"
rand= "0.6"
serde_json= "1.0"
rs_tracing= { version = "1.0", features = ["rs_tracing"]}
reqwest= "0.9"

