[package]
name = "centralgithook"
version = "0.1.0"
authors = ["Christian Schilling <christian.schilling@esrlabs.com>"]

[dependencies]
git2 = "*"
clap = "2"
tempdir = "0.3.*"
log = "*"
fern = "*"
env_logger = "*"
regex = "*"
rouille = { git = "git://github.com/tomaka/rouille.git" }
thrussh = "*"
thrussh-keys = "*"
futures = "*"
tokio-core = "*"
ring = "*"
