[package]
name = "grib"
version = "0.1.0"
authors = ["Christian Schilling <christian.schilling@esrlabs.com>"]
build = "build.rs"

[build-dependencies]
git-version = "*"

[dependencies]
git2 = "*"
clap = "2"
tempdir = "0.3.*"
log = "*"
fern = "*"
env_logger = "*"
regex = "*"
futures = "*"
tokio-core = "0.1"
tokio-process = "0.1"
ring = "*"
lazy_static = "*"
hyper = "0.11"
futures-cpupool = "*"

